### ISSUE TITLE
Grunt issue

### ISSUE THREAD

**Issue by MarcioOliveira** [eduardoboucas/postcss-cssential#2]
When using grunt, it seems that the task is finished before the new html file is created. If this is the last task, grunt finishes without writing to the html file. I am using a workaround that is using a wait task to stall grunt for a second.

**Comment by eduardoboucas** [comment]
I believe this is because it's using `readFile` and not `readFileSync`. I'll try to look into this soon.

**Comment by eduardoboucas** [comment]
Closed via #3.
